### ISSUE TITLE
Special symbols causing issues with scipiper?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/scipiper#151]
I think I have uncovered a weird edge case. I think a special character/symbol is causing `scipiper` to throw an error when it shouldn't. 

I am working on parsing some files in the lake-temperature-model-prep repository. The files I am writing a parser for have the column name `Temp (°C)`. The column appears in hundreds of files, so just changing it manually is not a great solution. I am using `df %>% rename(temp = "Temp (°C)")` in my function called by `scipiper` to process the data to use our chosen common name for temperature data.

Below is my reproducible example of this issue.

```r
library(dplyr)

# For example, I have this data
df <- tibble(x = 1, `Temp (°C)` = 6)

# I can easily parse using rename
rename(df, temp = "Temp (°C)")
```

I decided to try it within a teeny makefile. Running `scmake("df_parsed")` and the `remake.yml` below works with no errors 👍
```
packages:
  - dplyr

targets:
  df:
    command: tibble(x = 1, `Temp (°C)` = 6)
  df_parsed:
    command: rename(df, temp = I("Temp (°C)"))
```

I also tried saving and then reading the df in as a file since that is what happens in my actual code. This still works when you run `scmake("df_parsed")` ...
```
packages:
  - dplyr

targets:
  df:
    command: tibble(x = 1, `Temp (°C)` = 6)
  df.rds:
    command: saveRDS(file = target_name, object = df)
  df_read:
    command: readRDS("df.rds")
  df_parsed:
    command: rename(df_read, temp = I("Temp (°C)"))
```

BUT if I first save the RDS outside of the pipeline AND THEN try to read that file in the makefile, it breaks when I run `scmake("df_parsed)` 🤯 

```r
df <- tibble(x = 1, `Temp (°C)` = 6)
saveRDS(df, "df_outside.rds")
```
```
packages:
  - dplyr

targets:
  df_read:
    command: readRDS("df_outside.rds")
  df_parsed:
    command: rename(df_read, temp = I("Temp (°C)"))
```

It shows this:

```r
> x <- scmake("df_parsed")
Starting build at 2021-09-13 11:54:12
<  MAKE > df_parsed
[ BUILD ] df_read   |  df_read <- readRDS("df_outside.rds")
[  READ ]           |  # loading packages
[ BUILD ] df_parsed |  df_parsed <- rename(df_read, temp = "Temp (Â°C)")
Error: Can't rename columns that don't exist.
x Column `Temp (Â°C)` doesn't exist.
```

I don't think it has to do with the RDS files because in my real example where it is breaking, the files are xlsx. So, I think it is something with how `scipiper` is interacting with the files created outside of the `scipiper` pipeline. Not sure where to go from here? 

It truly seems to be a difference with how it is treating the special symbol. For example, I added this to see if I could get around it by using base R methods:

![image](https://user-images.githubusercontent.com/13220910/133126284-c8beefe4-ee6e-491b-8cd7-b8635edbe30f.png)

When I run `scmake()` and pause at the browser, now the code looks like this:

![image](https://user-images.githubusercontent.com/13220910/133126255-f7b72df5-b81c-467b-836d-ca29964e9fa3.png)

... sorry for such a lengthy issue. Stuck and don't know what to search for to get unstuck since this seems like it is happening only when I run within the `scipiper` pipeline.

**Comment by lindsayplatt** [comment]
Currently exploring options related to changing the encoding thanks to [this stackoverflow about what the inserted `Â` symbol means](https://stackoverflow.com/questions/42966981/special-character-%C3%82-inserted-before-copyright-symbol) and [this stackoverflow about how someone changed file encoding in R](https://stackoverflow.com/questions/34024654/reading-rdata-file-with-different-encoding).

**Comment by lindsayplatt** [comment]
OK, so I was able to overcome this issue by changing the encoding from `UTF-8` to `latin1` on my data's column names (see this commit: https://github.com/lindsayplatt/lake-temperature-model-prep/commit/9fd7b701a87dce47506ab17a57866526f8fbcce1). Not sure what this means for `scipiper`. Do we close this issue and know we can return to this documented fix in the future should it ever come up again?

**Comment by aappling-usgs** [comment]
Nice sleuthing, Lindsay. To make it extra fun, I can't reproduce your issue on my mac. Out of curiosity, what is `names(fetch('df_read'))` as produced by this pipeline?
```yml
packages:
  - dplyr

targets:
  df:
    command: tibble(x = 1, `Temp (°C)` = 6)
  df.rds:
    command: saveRDS(file = target_name, object = df)
  df_read:
    command: readRDS("df.rds")
  df_parsed:
    command: rename(df_read, temp = I("Temp (°C)"))
```

Given our transition toward targets, yes, I agree with not trying to fix this issue within scipiper for now. But if it comes up again and again while we're still using remake heavily, we can certainly work on it.
