### ISSUE TITLE
scmake(force=TRUE)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/scipiper#4]
Would be nice to be able to cause targets to rebuilt even if they're current. remake sorta pretends it can do this, but can't, with `update`. you can do it with remake by calling `delete` and then `make`, but one call would be better than two.

This gets extra interesting for task makefiles. We're headed toward this paradigm of a parent makefile like this '4_release_model.yml':
```yml
  model_sites_plan:
    command: create_model_sites_task_plan(metab.config, folders=model_release_folders)
    
  4e_model_sites.yml:
    command: create_model_sites_makefile(
      makefile=target_name, task_plan=model_sites_plan,
      template_file='../lib/task_makefile.mustache')

  ../4_data_release/log/4e_model_sites.ind:
    command: loop_model_tasks(
      job_target=I('4e_model_sites'), 
      task_plan=model_sites_plan, 
      task_makefile='4e_model_sites.yml')
```
which creates and calls a child (task) makefile '4e_model_sites.yml' whose overall target is this:
```yml
  # --- Overall job --- #

  4e_model_sites:
    command: write_timestamp(I('../4_data_release/log/4e_model_sites.ind'))
    depends: 
      - '../4_data_release/cache/models/post/nwis_01548303_input.tsv'
      - '../4_data_release/cache/models/post/nwis_03293000_input.tsv'
      - '../4_data_release/cache/models/post/nwis_01473500_input.tsv'
```
You can run all tasks the first time using
```r
remake::make('../4_data_release/log/4e_model_sites.ind', remake_file='4_release_models.yml')
```
but we've intentionally decoupled the main makefile from all the dependencies given in the job target of the task makefile, so it's not uncommon to need to force remake on the job target. Simply deleting the file (`file.remove('../4_data_release/log/4e_model_sites.ind')`) or even calling `remake::make('../4_data_release/log/4e_model_sites.ind', remake_file='4_release_models.yml')` doesn't do it. You need to ALSO `remake:delete('4e_model_sites', remake_file='4e_model_sites.yml)`. 

It would be swell if `scmake('../4_data_release/log/4e_model_sites.ind', remake_file='4_release_models.yml', force=TRUE)` was smart enough to do all that deleting for us before rebuilding. Maybe even while setting aside the deleted files during the build so they can be replaced if the build encounters errors (but that's optional icing on the cake).
