### ISSUE TITLE
add size and hash of data file to ind file build files

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/scipiper#40]
example of a current build file:
```yml
version: 0.3.0
name: 3_forecast/out/preds_loadest.rds.ind
type: file
hash: 4c3e2454d173831585e8009d686ce9ba
time: 2018-05-16 18:24:03 UTC
depends:
  forecast_df: 44ed1f468cefbc17eb2dd2a380ae8756
  forecast_plan: 23bdef57ad5beb6a0deb5e67e1d6e500
  lib/cfg/gd_config.yml: cf9c52868594c233f17a6f751a553018
fixed: b26a7577dedb6ce133d4fe20a172d331
code:
  functions:
    gather_forecasts: 9d2e514d082a7529a9853e926ef084b8
```
i end up reading these files in commits and PRs pretty often, so info relevant to humans should go here. and if i remember right, adding bonus information to these files wouldn't hurt the remake process because we just wouldn't copy it over to remake's version of the status file.

just need to be resilient to cases where there is no data file, or it's not local, that corresponds to the ind file. one possible implementation would be to (1) copy the contents of ind files, or at least the first 10 lines or something, straight into these build files, and then (2) add more info to standard .ind files created by gd_put, sc_put, sc_indicate(data_file=xx), etc.
