### ISSUE TITLE
`complete` .ind files in task plans could store data hash

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/scipiper#49]
I think they could, anyway. I'm looking at a preliminary task remake file from the lake temperature stuff, which has tasks like this:
```
 # --- NLDAS_7.12_223.223_141.141_dlwrfsfc.nc --- #		
  		
  1_nldas_cubes/out/NLDAS_7.12_223.223_141.141_dlwrfsfc.nc:		
    command: nccopy_nldas(target_name)		
		
  ind_dir/NLDAS_7.12_223.223_141.141_dlwrfsfc.nc.ind:		
    command: sc_indicate(target_name)		
    depends:		
      - 1_nldas_cubes/out/NLDAS_7.12_223.223_141.141_dlwrfsfc.nc
```
(see https://github.com/USGS-R/lake-temperature-model-prep/pull/3/files?utf8=%E2%9C%93&diff=split#diff-989a07de296dcf114a762d038357bdf0)

I actually don't think it'll change behavior much, but could be helpful for interpretation of rebuilds, if we included hashes of the depends files within the .ind file created by sc_indicate.
