### ISSUE TITLE
support combiners in task tables

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/scipiper#52]
`sc_indicate` is great for a closing off a series of tasks w/ a single target. 

For the gridded data builds from NLDAS, I find myself needing to write a single summary file after all the tasks are done. In this case, it is `'0_config/in/nldas_cells.rds'`, which is a cheater file that provides an overview of existing data that informs the original data pulls. To include this in remake directly is a cyclical reference no-no, but it is important nonetheless, and I think you understand the pattern I am using. 

Anyhow, I am curious about the best way to connect the rebuild of that file to `sc_indicate`. I could: 
1) have a separate remake file that has a target that depends on the indicator file that gathers all of the targets in the big task plan. This would have the side-effect of updating that .rds file w/ the now current data
2) sc_indicate could accept a function as an optional argument, and could run that function as a final step to executing its normal duties. In this case I would do something like `sc_indicate(ind_file = "example.ind", exit_function = summarize_nldas_cells(cells_dir, '0_config/in/nldas_cells.rds'))` but I see that would be definitely more complex

I think we have kicked around some thoughts related to a more explicit "combine" method available to `scipiper`. This is one potential use-case where such a method would be really helpful.

**Comment by jread-usgs** [comment]
Another use-case for this:

I've got a bunch of netcdf files, and I want to spawn a bunch of feather files from those netcdf files. Since there is significant overhead in opening and closing the netcdf files, I would like to

**Comment by aappling-usgs** [comment]
Thanks for these thoughts. I appreciate the specific use case and agree that something is needed here. Rather than overloading `sc_indicate`, I'd propose that we allow additional combine operations as part of `create_task_makefile`, which could then still be responsible for producing a single "I'm all done!" indicator with `sc_indicate` but which could also permit any number of combination operations that depend on the completion of intermediate steps.

`create_task_makefile(task_plan, combine_plan[new], [...other args...])`

**Comment by jread-usgs** [comment]
I'm working through the code a bit and re-familiarizing myself w/ how `scipiper` "completes" the task tables. 

Currently, we can tie together the final steps in each task as depends of a single indicator file (the default), or we can `hash_dependencies()` to keep the result as an object in R (in this case a vector of the hashes). These are set by `ind_complete = TRUE` and `FALSE`, respectively. 

The missing piece of functionality as I understand it is to have a third option for combining previous targets into a single output file/object. I am having trouble coming up with justification for why this third option shouldn't be fairly rigid - for example, a reference to a function that takes a bunch of target names from the `final_steps` of the task plan and generates a single output (a function of the form `function(target_name, ...){}`). This task makefile would likely have an additional target - which would be the .ind of the output of the combiner - as the `target_default`, but with the option to skip indicating and instead have the file/object combined output be the default. 

If we agree this is the way to move forward, I will work on code. For the syntax, I think this concept is really similar to `tryCatch`'s `finally`, so I'd like to consider using that as a new arg. 

Something like this?

```yml
target_default: states

packages:
  - mda.streams

file_extensions:
  - "ind"

targets:
  # --- AZ --- #
  
  AZ_prep:
    command: process(target_name, I('C'))
    depends:
      - A
      - B

  AZ_plot:
    command: visualize('AZ', 'Phoeniz')

  # --- CA --- #
  
  CA_prep:
    command: process(target_name, I('C'))
    depends:
      - A
      - B

  CA_plot:
    command: visualize('CA', 'Sacramento')

  # --- CO --- #
  
  CO_prep:
    command: process(target_name, I('C'))
    depends:
      - A
      - B

  CO_plot:
    command: visualize('CO', 'Denver')

  # --- Finally --- #

  states_report:
    command: my_combiner(target_name=target_name, 
        AZ_plot,
        CA_plot,
        CO_plot)

  # --- Overall job --- #

  log/states.ind:
    command: sc_indicate(target_name)
    depends:
      - states_report

```
