### ISSUE TITLE
could we use `sc_indicate` to give us a hash table for several local files?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/scipiper#74]
I love what `sc_indicate` produces from 

```yaml
8_drivers_munge_tasks:
    command: sc_indicate(I('8_drivers_munge/out/8_drivers_munge_tasks.ind'), hash_depends=I(TRUE), depends_target=I('8_drivers_munge_tasks'), depends_makefile=I('8_drivers_munge_tasks.yml'))
    depends: 
      - ...
```
which is this:
```yaml
8_drivers_munge/out/NLDAS_time[0.346848]_x[284]_y[144].csv.ind: a75f2789336c8626c2de19b7e72731f0
8_drivers_munge/out/NLDAS_time[0.346848]_x[250]_y[169].csv.ind: 88083431fb49a37316682b6eb0be3bed
8_drivers_munge/out/NLDAS_time[0.346848]_x[242]_y[177].csv.ind: ce6b055b602eb803d5d6ffdd013a9461
8_drivers_munge/out/NLDAS_time[0.346848]_x[244]_y[177].csv.ind: f798f371fe79f9d1cb0a10435204f0b4
8_drivers_munge/out/NLDAS_time[0.346848]_x[243]_y[179].csv.ind: 09e02bce6fb6c49275f8dd99fc300768
8_drivers_munge/out/NLDAS_time[0.346848]_x[246]_y[179].csv.ind: c28b43084a3ef4d7598f3e74b5368126
8_drivers_munge/out/NLDAS_time[0.346848]_x[260]_y[183].csv.ind: 51207ab200f6343a74b803c13854e627
8_drivers_munge/out/NLDAS_time[0.346848]_x[258]_y[187].csv.ind: 0a442d50e4c48e5b8dff89a6a5e87bb7
8_drivers_munge/out/NLDAS_time[0.346848]_x[255]_y[188].csv.ind: 07964a7212182889ce9f65566c716f2d
8_drivers_munge/out/NLDAS_time[0.346848]_x[221]_y[132].csv.ind: ffe4752c4dee581fe8738c80aeb8cf78
8_drivers_munge/out/NLDAS_time[0.346848]_x[344]_y[196].csv.ind: d37c564497dd708583f799a6aba46cd2

```
This is a nice hash table that we could use to hold the coordinates of one-to-many target inputs.  The target output would just be one file, this hash .ind file, but it points to the many files generated within a function that created it. 

Here is a use-case:
I have a huge .nc file, and I need to write 2000 files from it. A normal `scipiper` workflow is to make a task table where each of those 2000 files is a task, and each of those tasks opens the .nc file, takes what it needs, closes the .nc, then writes the file. Trouble is, this is prohibitively slow. So, we need a way to open that .nc file once, take all 2000 files worth of data, write the files, then close the .nc file. 

So, what I'd like to do is something like 
```r
sc_indicate(ind_file = 'example_many.ind', data_file = c('8_drivers_munge/out/NLDAS_time[0.346848]_x[344]_y[196].csv', '8_drivers_munge/out/NLDAS_time[0.346848]_x[284]_y[144].csv'))
```
Then `'example_many.ind'` can be an input to a later function that wraps `create_task_plan()` where I can read that hash table, and use it to generate my task list. 

Currently this doesn't work because `data_file` inputs are length 1, and the hash when you use `data_file` doesn't include the file name. Using `depends_target` would work, but I'd have to create a fake remake.yaml as a workaround. 

Bad idea? We've used similar table outputs in the past (I think the internal analytics viz uses this principle w/ a .csv table).

**Comment by jread-usgs** [comment]
Could look like this:

```r
sc_indicate(ind_file = '', data_file = c('8_drivers_munge/out/NLDAS_time[0.346848]_x[344]_y[196].csv', '8_drivers_munge/out/NLDAS_time[0.346848]_x[284]_y[144].csv'))
$`8_drivers_munge/out/NLDAS_time[0.346848]_x[344]_y[196].csv`
[1] "35910bbf7e7522889e0ba36e590aadd0"

$`8_drivers_munge/out/NLDAS_time[0.346848]_x[284]_y[144].csv`
[1] "0823ba6a3db0073e2c6acb219c85887f"

sc_indicate(ind_file = '', data_file = '8_drivers_munge/out/NLDAS_time[0.346848]_x[344]_y[196].csv')
$hash
[1] "35910bbf7e7522889e0ba36e590aadd0"
```

**Comment by jread-usgs** [comment]
I tried this out for my use-case, and it seemed to perform well. Instead of one task per cell feather file, I have one task per variable that writes all files and uses `sc_indicate` to generate a yaml that holds the filepaths and hashes for each of the files created. So a task looks like this:

```yaml
  # --- cellgroup_time[0.346848]_var[tmp2m].yml --- #
  
  6_drivers/log/feather/cellgroup_time[0.346848]_var[tmp2m].yml:
    command: cubes_to_cell_files(target_name, cells = nldas_new_cells, out_dir = I('6_drivers/out/feather'),nc_dir = I('6_drivers/out/nc'), 
       '6_drivers/log/nc/NLDAS_time[000000.024999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[025000.049999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[050000.074999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[075000.099999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[100000.124999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[125000.149999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[150000.174999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[175000.199999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[200000.224999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[225000.249999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[250000.274999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[275000.299999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[300000.324999]_x[221.344]_y[132.196]_var[tmp2m].nc.ind',
       '6_drivers/log/nc/NLDAS_time[325000.346848]_x[221.344]_y[132.196]_var[tmp2m].nc.ind')
```
and the output (truncated) looks like this (from 6_drivers/log/feather/cellgroup_time[0.346848]_var[tmp2m].yml) : 
```yaml
6_drivers/out/feather/NLDAS_time[0.346848]_x[311]_y[134]_var[tmp2m].feather: a3d9f6ae8f37d38f08482dfa1b44f7eb
6_drivers/out/feather/NLDAS_time[0.346848]_x[312]_y[134]_var[tmp2m].feather: 577628006d282c34877e226ee4b5592c
6_drivers/out/feather/NLDAS_time[0.346848]_x[313]_y[134]_var[tmp2m].feather: 40aa69b62af6e59cd1556d4d143efd43
6_drivers/out/feather/NLDAS_time[0.346848]_x[314]_y[134]_var[tmp2m].feather: b31f0b89139cfe663a8fe0a41c98e43e
6_drivers/out/feather/NLDAS_time[0.346848]_x[315]_y[134]_var[tmp2m].feather: 2aba97db3bbf86df8b36a5e6b16eaa6f
6_drivers/out/feather/NLDAS_time[0.346848]_x[316]_y[134]_var[tmp2m].feather: 00754639e2c94dae02f5b5e3ac1c235a
6_drivers/out/feather/NLDAS_time[0.346848]_x[317]_y[134]_var[tmp2m].feather: 0db990fab089f2f78bad66f099a7189d
6_drivers/out/feather/NLDAS_time[0.346848]_x[318]_y[134]_var[tmp2m].feather: 7a5b87b6bd97249222b5a705b8f87685
6_drivers/out/feather/NLDAS_time[0.346848]_x[319]_y[134]_var[tmp2m].feather: a8aaa04c25f566a4831d0d14c469b1e2
6_drivers/out/feather/NLDAS_time[0.346848]_x[320]_y[134]_var[tmp2m].feather: bc55b56b14e35b4edb2325851d5bca96
6_drivers/out/feather/NLDAS_time[0.346848]_x[322]_y[134]_var[tmp2m].feather: c82724eaa83639f6b23ea6e1e3ab54ee
6_drivers/out/feather/NLDAS_time[0.346848]_x[323]_y[134]_var[tmp2m].feather: 67133c44a8827dd47c1b5895fb0bdc0b
6_drivers/out/feather/NLDAS_time[0.346848]_x[324]_y[134]_var[tmp2m].feather: 15c96d3ce7091da200ac8f704a154ff8
6_drivers/out/feather/NLDAS_time[0.346848]_x[325]_y[134]_var[tmp2m].feather: 445573ad097125c52e9ac288bdf8bc41
6_drivers/out/feather/NLDAS_time[0.346848]_x[311]_y[135]_var[tmp2m].feather: 1c1a3cd6a2d61abe5a8fd412c8366856
```
I re-wrote the .csv tasks (these build the multi-variable driver file output) to include an additional step that filters this hash table into only the files that go into each individual driver file:
```yaml
  # --- NLDAS_time[0.346848]_x[322]_y[134].csv --- #
  
  NLDAS_time_0.346848_x_322_y_134_cell_group_table:
    command: filter_cell_group_table(cell_group_table, pattern = I('time\\[0.346848\\]_x\\[322\\]_y\\[134\\]'))

  8_drivers_munge/out/NLDAS_time[0.346848]_x[322]_y[134].csv:
    command: feathers_to_driver_file(target_name, cell_group_table = NLDAS_time_0.346848_x_322_y_134_cell_group_table)

  8_drivers_munge/out/NLDAS_time[0.346848]_x[322]_y[134].csv.ind:
    command: sc_indicate(target_name)
    depends:
      - 8_drivers_munge/out/NLDAS_time[0.346848]_x[322]_y[134].csv
```
This seems to be a good solution for me, but it would be great to discuss. The time to move through the 16K feather files as individual targets was projected to be 44 days(!), this pattern allowed me to build them in ~1.5hr.
