### ISSUE TITLE
simplest use of create_task_step needs ind_dir

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/scipiper#97]
```r
task_config <- data.frame(
  id=c('AZ','CO','CA'),
  capital=c('Phoeniz','Denver','Sacramento')
)
step1 <- create_task_step(
  step_name = 'prep',
  target = function(task_name, step_name, ...) {
    sprintf('%s_%s', task_name, step_name)
  },
  depends = c('A','B'),
  command = "process(target_name, I('C'))"
)
step2 <- create_task_step(
  step_name = 'plot',
  command = function(target_name, task_name, ...) {
    capital <- task_config[task_config$id == task_name, 'capital']
    sprintf('visualize(\'%s\', \'%s\')', task_name, capital)
  }
)
step3 <- create_task_step('report')
task_plan <- create_task_plan(c('AZ','CA','CO'), list(step1, step2, step3),
                              final_steps='report', ind_dir='states/log')
```
works as expected. Snippet of remake:
```yaml
  states/log/CA.ind:
    command: sc_indicate(target_name)
    depends:
      - CA_report
```
but leaving out the `ind_dir` creates bad target names for `sc_indicate`:
```yaml
  .ind:
    command: sc_indicate(target_name)
    depends:
      - CA_report
```
I think in this case, we'd want it to just name that ind target `CA.ind`
